# Generated by Django 4.1 on 2022-11-25 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0002_remove_produto_categoria_produto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nomeProduto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_produto',
        ),
    ]
